routes/web.php
<?php

use App\Http\Controllers\Front\DashboardController;
use App\Http\Controllers\Front\HomeController;
use App\Http\Controllers\Front\PaymentController;
use App\Http\Controllers\Front\ProductController;
use App\Http\Controllers\Front\SearchController;
use App\Http\Controllers\Panel\AuthController;
use App\Http\Controllers\Panel\CategoryController;
use App\Http\Controllers\Panel\CommentController;
use App\Http\Controllers\Panel\CreatorController;
use App\Http\Controllers\Panel\IndexController;
use App\Http\Controllers\Panel\MigrationOldSiteController;
use App\Http\Controllers\Panel\PostController;
use App\Http\Controllers\Panel\SubscribePlanController;
use App\Http\Controllers\Panel\UsersController;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('index');
})->name('home');*/


Route::get('/', [HomeController::class, 'index'])->name('index');

Route::get('/vip-buy', [HomeController::class, 'vip_buy'])->name('vipBuy');

Route::get('/blog', 'BlogController@blog')->name('blog');

Route::get('/about', 'PageController@about')->name('about');

Route::get('/contact', 'PageController@contact')->name('contact');

Route::get('/plus/{slug}', 'PostController@plus_single')->name('plusSingle');

Route::get('/product/{slug}', [ProductController::class, 'single'])->name('productSingle');

Route::get('/product-category/{slug}', 'CategoryController@product_category')->name('productCategory');

Route::get('/posts', 'TestController@show')->name('posts');

Route::get('/search',[SearchController::class,'search'])->name('search');

Route::post('/login', [AuthController::class, 'dashboard_login_perform'])->name('dashboardLoginConfirm');
Route::get('/login', [AuthController::class, 'dashboard_login'])->name('login');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'as' => 'dashboard.', 'middleware' => 'auth'], function () {

    Route::get('/', [DashboardController::class, 'dashboard'])->name('userAccount');
    Route::get('/orders', [DashboardController::class, 'orders'])->name('userOrders');
    Route::get('/downloads', [DashboardController::class, 'downloads'])->name('userDownloads');
    Route::get('/edit-address', [DashboardController::class, 'editAddress'])->name('userEditAddress');
    Route::get('/edit-account', [DashboardController::class, 'editAccount'])->name('userEditAccount');
    Route::post('/post/comment',[ProductController::class,'send_comment'])->name('sendComment');
    Route::get('/logout', [DashboardController::class, 'logout'])->name('logout');
});

Route::group(['prefix'=>'payment','namespace'=>'Payment','as'=>'payment.'],function (){

    Route::get('/', [PaymentController::class, 'payment'])->name('userPayment');
    Route::get('/verify', [PaymentController::class, 'verify'])->name('userPaymentVerify');

});


Route::get('/panel/login', [AuthController::class, 'login'])->name('panelLogin');
Route::post('panel/login/confirm', [AuthController::class, 'login_perform'])->name('loginPerform');
//Route::get('/old/posts',[MigrationOldSiteController::class,'user_migrate'])->name('migrate');

Route::group(['prefix' => 'panel', 'namespace' => 'Panel', 'as' => 'panel.', 'middleware' => ['auth', 'can:admin']], function () {

    Route::get('/index', [IndexController::class, 'index'])->name('index');

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

        #region Posts
        Route::get('/post/create', [PostController::class, 'create'])->name('postCreate');
        Route::post('/post/create', [PostController::class, 'store'])->name('postStore');
        Route::get('/post/json', [PostController::class, 'json'])->name('postJson');
        Route::get('/post/index', [PostController::class, 'index'])->name('postIndex');
        Route::get('/post/edit', [PostController::class, 'edit'])->name('postEdit');
        Route::post('/post/update/{id}', [PostController::class, 'patch'])->name('postPatch');
        Route::get('/post/delete', [PostController::class, 'delete'])->name('postDelete');

        Route::get('/post/replicate', [PostController::class, 'replicate'])->name('postReplicate');
        Route::post('/post/replicate-perform/{id}', [PostController::class, 'replicate_perform'])->name('postReplicatePerform');

        Route::get('/post/image/delete', [PostController::class, 'image_delete'])->name('postImageDelete');
        Route::get('/post/index-image/delete', [PostController::class, 'index_image_delete'])->name('postIndexImageDelete');
        #endregion

        #region Category
        Route::get('/category/json', [CategoryController::class, 'json'])->name('categoryJson');
        Route::get('/category/create', [CategoryController::class, 'create'])->name('categoryCreate');
        Route::post('/category/create', [CategoryController::class, 'store'])->name('categoryStore');
        Route::get('/category/edit/{id}', [CategoryController::class, 'edit'])->name('categoryEdit');
        Route::post('/category/edit/{id}', [CategoryController::class, 'patch'])->name('categoryPatch');
        Route::get('/category/delete', [CategoryController::class, 'json'])->name('categoryDelete');
        #endregion

        #region Creators
        Route::get('/creator/json', [CreatorController::class, 'json'])->name('creatorJson');
        Route::get('/creator/create', [CreatorController::class, 'create'])->name('creatorCreate');
        Route::post('/creator/create', [CreatorController::class, 'store'])->name('creatorStore');
        Route::get('/creator/edit/{id}', [CreatorController::class, 'edit'])->name('creatorEdit');
        Route::post('/creator/edit/{id}', [CreatorController::class, 'patch'])->name('creatorPatch');
        Route::get('/creator/delete', [CreatorController::class, 'json'])->name('creatorDelete');
        #endregion

        #region Users
        Route::get('/users/index', [UsersController::class, 'index'])->name('usersIndex');
        Route::get('/users/json', [UsersController::class, 'json'])->name('usersJson');
        Route::get('/user/create', [UsersController::class, 'create'])->name('userCreate');
        Route::post('/user/create', [UsersController::class, 'store'])->name('userStore');
        Route::get('/user/edit', [UsersController::class, 'edit'])->name('userEdit');
        Route::post('/user/edit', [UsersController::class, 'patch'])->name('userPatch');
        Route::get('/user/delete', [UsersController::class, 'json'])->name('userDelete');
        #endregion

        #region Vip Users
        Route::get('/users/vip/index', [UsersController::class, 'index_user_vip'])->name('usersVipIndex');
        Route::get('/user/renew', [UsersController::class, 'renew'])->name('userRenew');
        Route::post('/user/renew', [UsersController::class, 'patch_renew'])->name('userPatchRenew');
        Route::get('/users/vip/json', [UsersController::class, 'json_vip'])->name('usersVipJson');
        #endregion

        #region Subscribe Plans
        Route::get('/subscribe/plans/json', [SubscribePlanController::class, 'json'])->name('subscribePlanJson');
        Route::get('/subscribe/plans', [SubscribePlanController::class, 'plans'])->name('subscribePlan');
        Route::post('/subscribe/plan/create', [SubscribePlanController::class, 'store'])->name('subscribePlanStore');
        Route::get('/subscribe/plan/edit', [SubscribePlanController::class, 'edit'])->name('subscribePlanEdit');
        Route::post('/subscribe/plan/patch', [SubscribePlanController::class, 'patch'])->name('subscribePlanPatch');
        Route::get('/subscribe/plan/delete', [SubscribePlanController::class, 'delete'])->name('subscribePlanDelete');
        #endregion

        #region Comments
        Route::get('/comments',[CommentController::class,'index'])->name('commentIndex');
        Route::get('/comments/json',[CommentController::class,'json'])->name('commentJson');
        Route::get('/comment/edit',[CommentController::class,'edit'])->name('commentEdit');
        Route::post('/comment/approve',[CommentController::class,'approve'])->name('commentApprove');
        Route::post('/comment/reply',[CommentController::class,'reply'])->name('commentReply');
        Route::get('/comment/delete',[CommentController::class,'delete'])->name('commentDelete');
        #endregion

    });

    Route::get('/test', function () {
        return view('test');
    });

});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    Lfm::routes();
});

app/Http/Controllers/Panel/AuthController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    public function login()
    {
        if (!Auth::check())
            return view('panel.login');

        return redirect()->route('panel.index');
    }

    public function login_perform(Request $request)
    {
        $request->validate([
            'username' => 'required',
            'password' => 'required'
        ]);

        if (Auth::attempt([
            'username' => $request->username,
            'password' => $request->password
        ])) {
            return redirect()->route('panel.index');
        }

        return redirect()->back()->with('error', 'نام کاربری یا رمز عبور اشتباه است!');
    }

    public function logout()
    {
        Auth::logout();
        return redirect()->route('panelLogin');
    }

    public function dashboard_login()
    {
        if (!Auth::check())
            return view('front.login');

        return redirect()->route('dashboard.userAccount');
    }

    public function dashboard_login_perform(Request $request)
    {
        $request->validate([
            'username' => 'required',
            'password' => 'required'
        ]);

        if (Auth::attempt([
            'username' => $request->username,
            'password' => $request->password
        ])) {

            return redirect()->route('dashboard.userAccount');
        }

        return redirect()->back()->with('error', 'نام کاربری یا رمز عبور اشتباه است!');
    }
}

app/Http/Controllers/Panel/CategoryController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Helpers\Date;
use App\Helpers\ImageFactory;
use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;

class CategoryController extends Controller
{

    public function json()
    {
        $categories = Category::all()->sortByDesc('id');

        return Datatables::of($categories)
            ->addIndexColumn()
            ->addColumn('action', function ($category) {
                $btn = '<a href="' . route('panel.admin.categoryEdit', ['id' => $category->id]) . '" class="edit btn btn-primary btn-sm">ویرایش</a>' .
                    '<a href="' . route('panel.admin.categoryDelete', ['id' => $category->id]) . '"
                        onclick="return confirm(\'از انجام این عملیات مطمئن هستید؟\')" class="edit btn btn-danger btn-sm">حذف</a>';

                return $btn;
            })
            ->editColumn('post_count', function ($category) {
                return count($category->posts);
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function create()
    {
        return view('panel.posts.category_create',[
//            'categories' => Category::all()->sortByDesc('id'),
            'category_types' => Category::category_type(),
        ]);
    }

    public function store(Request $request)
    {
        $request->validate([
           'name' => 'required',
           'parent_id' => 'required'
        ]);

        try {

            $imageName = null;
            if ($request->file())
                $imageName = ImageFactory::upload($request->file('image'),public_path('uploads/categories/images'));



            $category = new Category();
            $category->name = $request->name;
            $category->description = $request->description;
            $category->slug = $request->slug ? $request->slug :  Str::slug($request->name,'-');
            $category->parent_id = $request->parent_id;
            $category->image = $imageName;
//            $category->type = $request->type;
            $category->save();


            return redirect()->back()->with('success','عملیات با موفقیت انجام شد');
        }
        catch (\Exception $exception)
        {
            return redirect()->back()->with('error',$exception->getMessage());
        }

    }

    public function edit($id)
    {
        return view('panel.posts.category_edit',[
            'category' => Category::findOrFail($id),
//            'categories' => Category::all()->sortByDesc('id'),
            'category_types' => Category::category_type(),
        ]);
    }

    public function patch(Request $request,$id)
    {
        $request->validate([
            'name' => 'required',
            'parent_id' => 'required'
        ]);

        try
        {
            $imageName = null;
            if ($request->file())
                $imageName = ImageFactory::upload($request->file('image'),public_path('uploads/categories/images'));

            $category = Category::findOrFail($id);
            $category->name = $request->name;
            $category->description = $request->description;
            $category->slug = $request->slug;
            $category->parent_id = $request->parent_id;
            $category->image = $request->file() ? $imageName : $category->image;
//            $category->type = $request->type;
            $category->save();

            return redirect()->back()->with('success','عملیات با موفقیت انجام شد');
        }
        catch (\Exception $exception)
        {
            return  redirect()->back()->with('error',$exception->getMessage());
        }

    }
}

app/Http/Controllers/Panel/CreatorController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Helpers\Date;
use App\Helpers\ImageFactory;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Creator;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;

class CreatorController extends Controller
{

    public function json()
    {
        $creators = Creator::all()->sortByDesc('id');

        return Datatables::of($creators)
            ->addIndexColumn()
            ->addColumn('action', function ($creator) {
                $btn = '<a href="' . route('panel.admin.creatorEdit', ['id' => $creator->id]) . '" class="edit btn btn-primary btn-sm">ویرایش</a>' .
                    '<a href="' . route('panel.admin.creatorDelete', ['id' => $creator->id]) . '"
                        onclick="return confirm(\'از انجام این عملیات مطمئن هستید؟\')" class="edit btn btn-danger btn-sm">حذف</a>';

                return $btn;
            })
            ->editColumn('post_count', function ($creator) {
                return is_array($creator->posts) ? count($creator->posts) : 0;
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function create()
    {
        return view('panel.posts.creator.creator_create');
    }

    public function store(Request $request)
    {
        $request->validate([
           'name' => 'required',
           'slug' => 'required',
        ]);


        try {

            $creator = new Creator();
            $creator->title = $request->name;
            $creator->slug = $request->slug;
            $creator->description = $request->description;
            $creator->save();

            return redirect()->back()->with('success','عملیات با موفقیت انجام شد');
        }
        catch (\Exception $exception)
        {
            return redirect()->back()->with('error',$exception->getMessage());
        }

    }

    public function edit($id)
    {
        return view('panel.posts.creator.creator_edit',[
            'creator' => Creator::findOrFail($id),
//            'category_types' => Category::category_type(),
        ]);
    }

    public function patch(Request $request,$id)
    {

        $request->validate([
            'name' => 'required',
            'slug' => 'required'
        ]);

        try
        {
            $category = Creator::findOrFail($id);
            $category->title = $request->name;
            $category->description = $request->description;
            $category->slug = $request->slug;

            $category->save();

            return redirect()->back()->with('success','عملیات با موفقیت انجام شد');
        }
        catch (\Exception $exception)
        {
            return  redirect()->back()->with('error',$exception->getMessage());
        }

    }
}

app/Http/Controllers/Panel/IndexController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    //
    public function index()
    {
        return view('panel.index');
    }
}

resources/views/panel/posts/category_create.blade.php
@extends('panel.layouts.master-panel')
@section('content')
    <div class="row">
        <div class="col-md-6 col-xs-12">

            <div class="x_panel">
                <div class="x_title">
                    <h2>افزودن دسته جدید

                    </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">تنظیمات 1</a>
                                </li>
                                <li><a href="#">تنظیمات 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <!-- start form for validation -->
                    <form method="post" action="{{route('panel.admin.categoryStore')}}"
                          id="demo-form" data-parsley-validate enctype="multipart/form-data">

                        @csrf
                        <label for="fullname"> نام <span class="required">*</span> :</label>
                        <input type="text" id="name" class="form-control" name="name" required/>

                        <br>

                        <label for="email">نامک :</label>
                        <input type="text" id="slug" class="form-control" name="slug"/>

                        <br>

                        {{--<label for="message">توضیحات</label>
                        <textarea name="description" class="form-control"></textarea>

                        <br>--}}

                        {{--<label for="fullname"> تصویر :</label>
                        <input type="file" id="image" class="form-control" name="image"/>

                        <br>--}}

                        {{--<label for="heard">نوع دسته<span class="required">*</span>:</label>
                        <select id="type" name="type" class="form-control select2">
                            @foreach($category_types as $key => $type)
                                <option value="{{$key}}">{{$type}}</option>
                            @endforeach
                        </select>

                        <div></div>
                        <br>--}}

                        <label for="heard">دسته اصلی<span class="required">*</span>:</label>
                        <select id="parent_id" name="parent_id" class="form-control select2">
                            <option value="0">مادر</option>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                        </select>

                        <div></div>
                        <br/>
                        <button type="submit" class="btn btn-primary">ثبت</button>

                    </form>
                    <!-- end form for validations -->

                </div>
            </div>


        </div>

        <div class="col-md-6 col-xs-12">

            <div class="x_panel">
                <div class="x_title">
                    <h2>لیست دسته ها
                        {{--<small>عناصر فرم های مختلف</small>--}}
                    </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">تنظیمات 1</a>
                                </li>
                                <li><a href="#">تنظیمات 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <div class="table-responsive">
                        <table id="categories_table" class="table table-striped jambo_table"
                               data-href="{{route('panel.admin.categoryJson')}}">
                            <thead>
                            <tr class="headings">

                                <th class="column-title text-center">No</th>
                                <th class="column-title text-center">عنوان</th>
                                <th class="column-title text-center">نامک</th>
                                <th class="column-title text-center">تعداد نوشته</th>
                                <th class="column-title no-link last text-center"><span
                                        class="nobr">عملیات</span>
                                </th>

                            </tr>
                            </thead>

                            <tbody class="text-center">

                            </tbody>
                        </table>
                    </div>


                </div>
            </div>

        </div>
    @endsection

    @section('css')
        <!-- select2 -->
            <link href="{{asset('panel/vendors/select2/dist/css/select2.css')}}" rel="stylesheet">
    @stop

    @section('js')
        <!-- CKEditor init -->
           {{-- <script src="//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.5.11/ckeditor.js"></script>
            <script src="//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.5.11/adapters/jquery.js"></script>--}}

            <!-- Select2 -->
            <script src="{{asset('panel/vendors/select2/dist/js/select2.js')}}"></script>

            {{--<script>
                var route_prefix = "/filemanager";
            </script>

            <script>
                $('textarea[name=description]').ckeditor({
                    height: 250,
                    language: 'fa',
                    filebrowserImageBrowseUrl: route_prefix + '?type=Images',
                    filebrowserImageUploadUrl: route_prefix + '/upload?type=Images&_token={{csrf_token()}}',
                    filebrowserBrowseUrl: route_prefix + '?type=Files',
                    filebrowserUploadUrl: route_prefix + '/upload?type=Files&_token={{csrf_token()}}'
                });
            </script>--}}

            <script>
                $(document).ready(function () {
                    $("#parent_id").select2();
                    $("#type").select2();
                });
            </script>
@stop

resources/views/panel/posts/post_index.blade.php
@extends('panel.layouts.master-panel')
@section('content')
    <div class="row">

        <div class="x_panel">
            <div class="x_title">
                <h2>نوشته ها
                    {{--<small>عناصر فرم های مختلف</small>--}}
                </h2>
                <a href="{{route('panel.admin.postCreate')}}" target="_blank" class="btn btn-success">نوشته جدید</a>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">تنظیمات 1</a>
                            </li>
                            <li><a href="#">تنظیمات 2</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <div class="table-responsive">
                    <table id="posts_table" class="table table-striped jambo_table"
                           data-href="{{route('panel.admin.postJson')}}">
                        <thead>
                        <tr class="headings">

                            <th class="column-title text-center">No</th>
                            <th class="column-title text-center">عنوان</th>
                            <th class="column-title no-link last text-center"><span
                                    class="nobr">عملیات</span>
                            </th>

                        </tr>
                        </thead>

                        <tbody class="text-center">

                        </tbody>
                    </table>
                </div>


            </div>
        </div>

    </div>
@endsection